apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /setters
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  name: istio-ingressgateway
  controlplanerevision: asm-managed
